def add(a, b):
	print "ADDING %d + %d" % (a, b)
	return a + b
	
def subtract (a, b):
	print "SUBTRACTING %d - %d" % (a, b)
	return a - b
	
def multiply (a, b):
	print "MULTIPLYING %d * %d" % (a, b)
	return a * b
	
def divide (a, b):
	print "DIVIDING %d / %d" % (a, b)
	return a / b
	
	
print "Let's do some maths with just functions!"

age = add(30, 5)
height = subtract (78, 4)
weight = multiply(90, 2)
iq = divide(100, 2)

print "Age: %d, Height: %d, Weight: %d, IQ: %d" % (age, height, weight, iq)

# A Puzzle for the extra credit, type it in anyway.
print "Here is a puzzle."

what = add(age, subtract(height, multiply(weight, divide(iq, 2))))
#(a + (b -(c * (d / 2))))

print "That becomes:", what, "Can you do it by hand?\n"

print "Testing 'a + b - c * d / 2' below...\n" #do it by hand!

test = age + height - weight * iq / 2 #remember, PEMDAS.
print test

if float(test) == float(what):		#| This is just a simple
	print "Correct.\n"				#| test to check if the value
else: print "Wrong. Try again.\n"	#| generated by what = the 'by hand' value

#own formula follows:
a = add(24, 34)
b = subtract(100, 1023)
c = divide(a, b)

print "ANSWER:\t\t", c, "\n"


# Mistake 1: multiple instead of multiply
# Mistake 2: %D instead of %d